spring.application.name=serverjava

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

jwt.secret=${JWT_SECRET}
server.port=${PORT:8080}